const feedActionTypes = {
  GETTING_FEED: "GETTING_FEED",
  SET_FEED: "SET_FEED",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  LIKE_POST: "LIKE_POST",
  UNLIKE_POST: "UNLIKE_POST",
  SAVE_POST: "SAVE_POST",
  UNSAVE_POST: "UNSAVE_POST",
  SET_POST_LIKERS: "SET_POST_LIKERS",
  GETTING_LIKERS: "GETTING_LIKERS",
  DELETE_POST: "DELETE_POST",
  UPLOAD_POST: "UPLOAD_POST",
};

export default feedActionTypes;
