const postActionTypes = {
  LOADING_POST: "LOADING_POST",
  SET_POST: "SET_POST",
  ERROR_IN_POST: "ERROR_IN_POST",
  LIKE_P_POST: "LIKE_P_POST",
  UNLIKE_P_POST: "UNLIKE_P_POST",
  SAVE_P_POST: "SAVE_P_POST",
  UNSAVE_P_POST: "UNSAVE_P_POST",
  GETTING_P_LIKERS: "GETTING_P_LIKERS",
  SET_P_POST_LIKERS: "SET_P_POST_LIKERS",
  DELETE_P_POST: "DELETE_P_POST",
};

export default postActionTypes;
