const postActionTypes = {
  ADDING_COMMENT: "ADD_COMMENT",
  ADD_COMMENT: "ADD_COMMENT",
  GETTING_COMMENTS: "GETTING_COMMENTS",
  ADD_COMMENTS: "ADD_COMMENTS",
  LOADING_EXPLORE_POSTS: "LOADING_EXPLORE_POSTS",
  ADD_EXPLORE_POSTS: "ADD_EXPLORE_POSTS",
  GETTING_FEED: "GETTING_FEED",
  SET_FEED: "SET_FEED",
  GETTING_POST: "GETTING_POST",
  ADD_POST: "ADD_POST",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  LIKE_POST: "LIKE_POST",
  UNLIKE_POST: "UNLIKE_POST",
  SAVE_POST: "SAVE_POST",
  UNSAVE_POST: "UNSAVE_POST",
  SET_POST_LIKERS: "SET_POST_LIKERS",
  GETTING_LIKERS: "GETTING_LIKERS",
  DELETE_POST: "DELETE_POST",
  UPLOAD_POST: "UPLOAD_POST",
};

export default postActionTypes;
