const profileActionTypes = {
  LOADING_PROFILE: "LOADING_PROFILE",
  SET_PROFILE: "SET_PROFILE",
  GET_FOLLOWERS: "GET_FOLLOWERS",
  GET_FOLLOWING: "GET_FOLLOWING",
  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  ERROR_IN_PROFILE: "ERROR_IN_PROFILE",
  SET_FOLLOWERS: "SET_FOLLOWERS",
  SET_FOLLOWINGS: "SET_FOLLOWINGS",
  LOADING_FOLLOWERS_OR_FOLLOWING_LIST: "LOADING_FOLLOWERS_OR_FOLLOWING_LIST",
};

export default profileActionTypes;
