const profileActionTypes = {
  LOADING_PROFILE: "LOADING_PROFILE",
  SET_PROFILE: "SET_PROFILE",
  GET_FOLLOWERS: "GET_FOLLOWERS",
  GET_FOLLOWING: "GET_FOLLOWING",
  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  ERROR_IN_PROFILE: "ERROR_IN_PROFILE",
};

export default profileActionTypes;
