const userActionTypes = {
  LOADING: "LOADING",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  GET_USER_DATA: "GET_USER_DATA",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  LOGOUT: "LOGOUT",
  SET_RECOMMENDED_USERS: "SET_RECOMMENDED_USERS",
};

export default userActionTypes;
